name: CI

on:
  # Triggers the workflow on push events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  distribute:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Run unittests
        run: python -m unittest tests/test_merge_keys.py
      - name: Run distribute
        run: python src/distribute.py
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          DISTRIBUTION_TARGETS: ${{ secrets.DISTRIBUTION_TARGETS }}
